version: "3.9"

services:
  app: 
    container_name: wallaclone-client
    image: node:16.14-alpine3.14
    restart: always
    volumes: 
      - ./:/app:cached
    working_dir: /app
    ports:
      - 3000:3000
    command: npm start
    tty: true